// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.30.2
// source: air_quality_monitoring.proto

package protoc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AirQualityMonitoring_SendDataToIngsetion_FullMethodName         = "/air_quality_monitoring.AirQualityMonitoring/SendDataToIngsetion"
	AirQualityMonitoring_SendDataToStorage_FullMethodName           = "/air_quality_monitoring.AirQualityMonitoring/SendDataToStorage"
	AirQualityMonitoring_ReceiveDataFromLocalStorage_FullMethodName = "/air_quality_monitoring.AirQualityMonitoring/ReceiveDataFromLocalStorage"
	AirQualityMonitoring_SendToAggregatedStorage_FullMethodName     = "/air_quality_monitoring.AirQualityMonitoring/SendToAggregatedStorage"
	AirQualityMonitoring_ReceiveAggregatedData_FullMethodName       = "/air_quality_monitoring.AirQualityMonitoring/ReceiveAggregatedData"
)

// AirQualityMonitoringClient is the client API for AirQualityMonitoring service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AirQualityMonitoringClient interface {
	// A simple RPC to send data to the ingestion service
	// and receive an acknowledgment
	SendDataToIngsetion(ctx context.Context, in *Data, opts ...grpc.CallOption) (*Ack, error)
	// A simple RPC to send data to the storage service
	// and receive an acknowledgment
	SendDataToStorage(ctx context.Context, in *Data, opts ...grpc.CallOption) (*Ack, error)
	// A simple RPC to request data from the local storage
	ReceiveDataFromLocalStorage(ctx context.Context, in *Data, opts ...grpc.CallOption) (*DataResponse, error)
	// A simple RPC to send data to the aggregated storage service
	SendToAggregatedStorage(ctx context.Context, in *Data, opts ...grpc.CallOption) (*Ack, error)
	// A simple RPC to request data from the aggregated storage
	ReceiveAggregatedData(ctx context.Context, in *Data, opts ...grpc.CallOption) (*DataResponse, error)
}

type airQualityMonitoringClient struct {
	cc grpc.ClientConnInterface
}

func NewAirQualityMonitoringClient(cc grpc.ClientConnInterface) AirQualityMonitoringClient {
	return &airQualityMonitoringClient{cc}
}

func (c *airQualityMonitoringClient) SendDataToIngsetion(ctx context.Context, in *Data, opts ...grpc.CallOption) (*Ack, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Ack)
	err := c.cc.Invoke(ctx, AirQualityMonitoring_SendDataToIngsetion_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *airQualityMonitoringClient) SendDataToStorage(ctx context.Context, in *Data, opts ...grpc.CallOption) (*Ack, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Ack)
	err := c.cc.Invoke(ctx, AirQualityMonitoring_SendDataToStorage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *airQualityMonitoringClient) ReceiveDataFromLocalStorage(ctx context.Context, in *Data, opts ...grpc.CallOption) (*DataResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DataResponse)
	err := c.cc.Invoke(ctx, AirQualityMonitoring_ReceiveDataFromLocalStorage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *airQualityMonitoringClient) SendToAggregatedStorage(ctx context.Context, in *Data, opts ...grpc.CallOption) (*Ack, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Ack)
	err := c.cc.Invoke(ctx, AirQualityMonitoring_SendToAggregatedStorage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *airQualityMonitoringClient) ReceiveAggregatedData(ctx context.Context, in *Data, opts ...grpc.CallOption) (*DataResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DataResponse)
	err := c.cc.Invoke(ctx, AirQualityMonitoring_ReceiveAggregatedData_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AirQualityMonitoringServer is the server API for AirQualityMonitoring service.
// All implementations must embed UnimplementedAirQualityMonitoringServer
// for forward compatibility.
type AirQualityMonitoringServer interface {
	// A simple RPC to send data to the ingestion service
	// and receive an acknowledgment
	SendDataToIngsetion(context.Context, *Data) (*Ack, error)
	// A simple RPC to send data to the storage service
	// and receive an acknowledgment
	SendDataToStorage(context.Context, *Data) (*Ack, error)
	// A simple RPC to request data from the local storage
	ReceiveDataFromLocalStorage(context.Context, *Data) (*DataResponse, error)
	// A simple RPC to send data to the aggregated storage service
	SendToAggregatedStorage(context.Context, *Data) (*Ack, error)
	// A simple RPC to request data from the aggregated storage
	ReceiveAggregatedData(context.Context, *Data) (*DataResponse, error)
	mustEmbedUnimplementedAirQualityMonitoringServer()
}

// UnimplementedAirQualityMonitoringServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAirQualityMonitoringServer struct{}

func (UnimplementedAirQualityMonitoringServer) SendDataToIngsetion(context.Context, *Data) (*Ack, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendDataToIngsetion not implemented")
}
func (UnimplementedAirQualityMonitoringServer) SendDataToStorage(context.Context, *Data) (*Ack, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendDataToStorage not implemented")
}
func (UnimplementedAirQualityMonitoringServer) ReceiveDataFromLocalStorage(context.Context, *Data) (*DataResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReceiveDataFromLocalStorage not implemented")
}
func (UnimplementedAirQualityMonitoringServer) SendToAggregatedStorage(context.Context, *Data) (*Ack, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendToAggregatedStorage not implemented")
}
func (UnimplementedAirQualityMonitoringServer) ReceiveAggregatedData(context.Context, *Data) (*DataResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReceiveAggregatedData not implemented")
}
func (UnimplementedAirQualityMonitoringServer) mustEmbedUnimplementedAirQualityMonitoringServer() {}
func (UnimplementedAirQualityMonitoringServer) testEmbeddedByValue()                              {}

// UnsafeAirQualityMonitoringServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AirQualityMonitoringServer will
// result in compilation errors.
type UnsafeAirQualityMonitoringServer interface {
	mustEmbedUnimplementedAirQualityMonitoringServer()
}

func RegisterAirQualityMonitoringServer(s grpc.ServiceRegistrar, srv AirQualityMonitoringServer) {
	// If the following call pancis, it indicates UnimplementedAirQualityMonitoringServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AirQualityMonitoring_ServiceDesc, srv)
}

func _AirQualityMonitoring_SendDataToIngsetion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Data)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AirQualityMonitoringServer).SendDataToIngsetion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AirQualityMonitoring_SendDataToIngsetion_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AirQualityMonitoringServer).SendDataToIngsetion(ctx, req.(*Data))
	}
	return interceptor(ctx, in, info, handler)
}

func _AirQualityMonitoring_SendDataToStorage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Data)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AirQualityMonitoringServer).SendDataToStorage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AirQualityMonitoring_SendDataToStorage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AirQualityMonitoringServer).SendDataToStorage(ctx, req.(*Data))
	}
	return interceptor(ctx, in, info, handler)
}

func _AirQualityMonitoring_ReceiveDataFromLocalStorage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Data)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AirQualityMonitoringServer).ReceiveDataFromLocalStorage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AirQualityMonitoring_ReceiveDataFromLocalStorage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AirQualityMonitoringServer).ReceiveDataFromLocalStorage(ctx, req.(*Data))
	}
	return interceptor(ctx, in, info, handler)
}

func _AirQualityMonitoring_SendToAggregatedStorage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Data)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AirQualityMonitoringServer).SendToAggregatedStorage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AirQualityMonitoring_SendToAggregatedStorage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AirQualityMonitoringServer).SendToAggregatedStorage(ctx, req.(*Data))
	}
	return interceptor(ctx, in, info, handler)
}

func _AirQualityMonitoring_ReceiveAggregatedData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Data)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AirQualityMonitoringServer).ReceiveAggregatedData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AirQualityMonitoring_ReceiveAggregatedData_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AirQualityMonitoringServer).ReceiveAggregatedData(ctx, req.(*Data))
	}
	return interceptor(ctx, in, info, handler)
}

// AirQualityMonitoring_ServiceDesc is the grpc.ServiceDesc for AirQualityMonitoring service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AirQualityMonitoring_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "air_quality_monitoring.AirQualityMonitoring",
	HandlerType: (*AirQualityMonitoringServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendDataToIngsetion",
			Handler:    _AirQualityMonitoring_SendDataToIngsetion_Handler,
		},
		{
			MethodName: "SendDataToStorage",
			Handler:    _AirQualityMonitoring_SendDataToStorage_Handler,
		},
		{
			MethodName: "ReceiveDataFromLocalStorage",
			Handler:    _AirQualityMonitoring_ReceiveDataFromLocalStorage_Handler,
		},
		{
			MethodName: "SendToAggregatedStorage",
			Handler:    _AirQualityMonitoring_SendToAggregatedStorage_Handler,
		},
		{
			MethodName: "ReceiveAggregatedData",
			Handler:    _AirQualityMonitoring_ReceiveAggregatedData_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "air_quality_monitoring.proto",
}
